### ISSUE TITLE
Steam disabling guard

### ISSUE THREAD

**Issue by ypc123** [steam-account-creator/Steam-Account-Generator#68]
![image](https://user-images.githubusercontent.com/10389186/69411514-2a6a2200-0d1e-11ea-81b0-d18dad71d0b5.png)

@EarsKilla Will there be a fix for this problem?

**Comment by EarsKilla** [comment]
It probably requires now to login again on steam and disable completely guard.  
But at this moment don't have enough time to debug and look what's happening while disabling guard and do something :(

**Comment by ypc123** [comment]
I wish it were fixed. 🙄 I don't like the site, I just like the program

**Comment by despa1r1337** [comment]
> I wish it were fixed. 🙄 I don't like the site, I just like the program

Try using version: v1.1.3.3

If you tried to open a program when it was already open, then you will not start it. Close the previous

**Comment by ypc123** [comment]
@despa1r1337 why do you insist on writing the same things, I also could not run the old version!

**Comment by MonteRider** [comment]
Still not worked. In manual type of confirmation generator just crushed on 2/5 checks of confirmation.

**Comment by boiamtrigger** [comment]
Hey there,
i have the same problem. Actually the program manages to disable the steam guard and steam sends an email to confirm the disabling. But i think somehow the program cant find the confirmation email.
